version: "3.4"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: web
    container_name: com_web
    ports:
      - "4000:4000"
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST_FRONT}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST_FRONT}
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: api
    container_name: com_api
    ports:
      - "4200:4200"
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST_API}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST_API}
  db:
    image: postgres
    restart: always
    container_name: com_db
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  adminer:
    image: adminer
    container_name: com_adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST_ADMINER}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST_ADMINER}
volumes:
  postgres:
networks:
  default:
    external:
      name: nginx-proxy
